<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import tensorflow as tf

test_mnist = tf.keras.datasets.mnist.load_data()
(x_train, x_test), (y_train, y_test) = test_mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])


# print(test_mnist)
print("[] ===== []")
print(model)


[] ===== []
<Sequential name=sequential_1, built=True>


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [13]:
check = model(x_train[:1])
print(check)
print(tf.argmax(check, axis=1))
print(" ")
print(check.numpy())

tf.Tensor(
[[0.1418199  0.08867972 0.05191378 0.09905788 0.13911435 0.0414344
  0.05002195 0.1630449  0.10960472 0.11530843]], shape=(1, 10), dtype=float32)
tf.Tensor([7], shape=(1,), dtype=int64)
 
[[0.1418199  0.08867972 0.05191378 0.09905788 0.13911435 0.0414344
  0.05002195 0.1630449  0.10960472 0.11530843]]


In [14]:
print(tf.nn.softmax(check).numpy())

[[0.10418765 0.09879564 0.09522928 0.09982629 0.10390615 0.09423655
  0.0950493  0.10642267 0.10088471 0.10146178]]


In [15]:
predictions = model(x_train[:1]).numpy()
predictions

tf.nn.softmax(predictions).numpy()

array([[0.10418765, 0.09879564, 0.09522928, 0.09982629, 0.10390615,
        0.09423655, 0.0950493 , 0.10642267, 0.10088471, 0.10146178]],
      dtype=float32)

In [16]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7911d8d7ad40>, kwargs={'from_logits': True, 'ignore_class': None})>


In [20]:
loss_fn(y_train[:1], predictions).numpy()

ValueError: Argument `output` must have rank (ndim) `target.ndim - 1`. Received: target.shape=(28, 28), output.shape=(1, 10)