<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Follow these tutorial: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=7FP5258xjs-v

In [1]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist.load_data() #####
(x_train, y_train), (x_test, y_test) = mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


# print(test_mnist)
print("[] ===== []")
print(model)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


[] ===== []
<Sequential name=sequential, built=True>


In [4]:
predictions = model(x_train[:1])
print(predictions)
print(tf.argmax(predictions, axis=1))
print(" ")
print(predictions.numpy())

tf.Tensor(
[[ 0.40307254  0.17571759 -0.25363666 -0.02485508  0.6565687  -0.06257631
   0.87941194  0.07439998 -0.5887401   0.1966913 ]], shape=(1, 10), dtype=float32)
tf.Tensor([6], shape=(1,), dtype=int64)
 
[[ 0.40307254  0.17571759 -0.25363666 -0.02485508  0.6565687  -0.06257631
   0.87941194  0.07439998 -0.5887401   0.1966913 ]]


In [5]:
print(tf.nn.softmax(predictions).numpy())

[[0.11907914 0.09486297 0.06174909 0.07762276 0.15343614 0.07474928
  0.19173759 0.08572254 0.0441669  0.09687361]]


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

tf.nn.softmax(predictions).numpy()

array([[0.11907914, 0.09486297, 0.06174909, 0.07762276, 0.15343614,
        0.07474928, 0.19173759, 0.08572254, 0.0441669 , 0.09687361]],
      dtype=float32)

In [7]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7cfd924b65c0>, kwargs={'from_logits': True, 'ignore_class': None})>


In [8]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.5936158)