<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_02-Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial from here:
https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2

In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


# **Initialization of Tensor**

In [6]:
x = tf.constant(2)
print(x)
x = tf.constant(4, shape=(1,3), dtype=tf.float64)
print(x)

x = tf.constant([[1,2,3],[4,5,6]]) # 123 dan 456 count as rows (2) 14 25 36 count as columns (3)
print(x)

x = tf.constant((1,2))
print(x)

for i in range(1,4):
    print(" ")

x = tf.ones(3,3)
print(x)
x = tf.zeros(2,3)
print(x)
x = tf.eye(3)
print(x)
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)
x = tf.range(start=1, limit=10, delta=3)
print(x)
#This will not change on the print, but its actually for change the type of the value. For example
#For example change from int to float like code down below
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float64)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
 
 
 
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.7296437   0.27943856 -0.33013526]
 [ 0.36843553 -0.42120633 -0.9439669 ]
 [-0.70628077  0.9781292  -0.03738477]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.6271329  0.78312874 0.0840404 ]
 [0.78087974 0.28499532 0.09464157]
 [0.12474895 0.47905755 0.11038733]], shape=(3, 3), dtype=float32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor([1. 4. 7.], shape=(3,), dtype=float64)


# **Mathematical Operation**

# **Indexing**

# **Reshaping**