<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import tensorflow as tf

test_mnist = tf.keras.datasets.mnist.load_data()
(x_train, x_test), (y_train, y_test) = test_mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])


# print(test_mnist)
print("[] ===== []")
print(model)


[] ===== []
<Sequential name=sequential_5, built=True>


In [9]:
check = model(x_train[:1])
print(check)
print(tf.argmax(check, axis=1))
print(" ")
print(check.numpy)

tf.Tensor(
[[0.07554609 0.06058553 0.03752242 0.13131642 0.08097802 0.0701722
  0.08655927 0.23215212 0.1724236  0.05274432]], shape=(1, 10), dtype=float32)
tf.Tensor([7], shape=(1,), dtype=int64)
 
<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.07554609, 0.06058553, 0.03752242, 0.13131642, 0.08097802,
        0.0701722 , 0.08655927, 0.23215212, 0.1724236 , 0.05274432]],
      dtype=float32)>>
