<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import tensorflow as tf

mnist = tf.keras.datasets.mnist.load_data()
(x_train, x_test), (y_train, y_test) = mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])


# print(test_mnist)
print("[] ===== []")
print(model)


[] ===== []
<Sequential name=sequential_3, built=True>


In [25]:
check = model(x_train[:1])
print(check)
print(tf.argmax(check, axis=1))
print(" ")
print(check.numpy())

tf.Tensor(
[[0.08802003 0.12566414 0.06973097 0.06206163 0.100933   0.06268991
  0.1136402  0.1525344  0.08098038 0.14374526]], shape=(1, 10), dtype=float32)
tf.Tensor([7], shape=(1,), dtype=int64)
 
[[0.08802003 0.12566414 0.06973097 0.06206163 0.100933   0.06268991
  0.1136402  0.1525344  0.08098038 0.14374526]]


In [26]:
print(tf.nn.softmax(check).numpy())

[[0.09876071 0.10254934 0.09697089 0.09623004 0.10004427 0.09629051
  0.10132367 0.10534222 0.09806792 0.10442041]]


In [27]:
predictions = model(x_train[:1]).numpy()
predictions

tf.nn.softmax(predictions).numpy()

array([[0.09876071, 0.10254934, 0.09697089, 0.09623004, 0.10004427,
        0.09629051, 0.10132367, 0.10534222, 0.09806792, 0.10442041]],
      dtype=float32)

In [28]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7911d8d7ad40>, kwargs={'from_logits': True, 'ignore_class': None})>


In [29]:
loss_fn(y_train[:1], predictions).numpy()

ValueError: Argument `output` must have rank (ndim) `target.ndim - 1`. Received: target.shape=(1, 28, 28), output.shape=(1, 10)