<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Follow these tutorial: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=7FP5258xjs-v

# **Set Up Tensorflow**

In [1]:
import tensorflow as tf
print('tf version:', tf.__version__)

tf version: 2.18.0


# **Load a Dataset**

In [2]:
mnist = tf.keras.datasets.mnist.load_data() #####
(x_train, y_train), (x_test, y_test) = mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


# **Build a machine learning model**

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


# print(test_mnist)
print("[] ===== []")
print(model)

[] ===== []
<Sequential name=sequential, built=True>


/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1])
print(predictions)
print(tf.argmax(predictions, axis=1))
print(" ")
print(predictions.numpy())

tf.Tensor(
[[-0.18900043 -0.29431996 -0.06984079  0.04490335 -0.10256311  0.28751066
   0.56442356 -0.19059058  0.1669034   0.19627908]], shape=(1, 10), dtype=float32)
tf.Tensor([6], shape=(1,), dtype=int64)
 
[[-0.18900043 -0.29431996 -0.06984079  0.04490335 -0.10256311  0.28751066
   0.56442356 -0.19059058  0.1669034   0.19627908]]


In [5]:
print(tf.nn.softmax(predictions).numpy())

[[0.07685801 0.06917504 0.08658437 0.09711186 0.08379699 0.12377566
  0.16326648 0.0767359  0.10971253 0.11298321]]


In [6]:
predictions = model(x_train[:1]).numpy()
predictions

tf.nn.softmax(predictions).numpy()

array([[0.07685801, 0.06917504, 0.08658437, 0.09711186, 0.08379699,
        0.12377566, 0.16326648, 0.0767359 , 0.10971253, 0.11298321]],
      dtype=float32)

In [7]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7d2b2441b920>, kwargs={'from_logits': True, 'ignore_class': None})>


In [8]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(2.0892844)

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# **Train and evaluate your model**

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.8551 - loss: 0.4929
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9532 - loss: 0.1574
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9668 - loss: 0.1081
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9725 - loss: 0.0863
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9762 - loss: 0.0759


In [11]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9770 - loss: 0.0739


[0.07390289008617401, 0.9769999980926514]

In [12]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.17249620e-07, 8.40080450e-09, 4.30948739e-06, 3.18651437e-04,
        5.78474768e-10, 1.91415165e-06, 2.02504791e-14, 9.99557436e-01,
        2.69245243e-06, 1.14886403e-04],
       [2.69277649e-07, 5.33737739e-06, 9.99979496e-01, 1.35394848e-05,
        1.27016428e-14, 3.56456383e-07, 1.32286928e-07, 3.31958289e-15,
        9.78094818e-07, 4.86702345e-10],
       [1.09673874e-05, 9.98817384e-01, 6.74787661e-05, 3.06676193e-05,
        9.71872214e-05, 8.89350213e-06, 8.07711403e-05, 2.94454483e-04,
        5.81590459e-04, 1.05095505e-05],
       [9.99795377e-01, 2.99938807e-09, 1.58629591e-05, 2.40655869e-08,
        1.15669104e-06, 4.43263752e-06, 1.63448000e-04, 8.30751924e-06,
        1.04818056e-07, 1.13475298e-05],
       [4.22015404e-07, 5.75328452e-09, 5.72108656e-05, 1.31632788e-07,
        9.97836173e-01, 3.30486591e-06, 3.45784588e-06, 5.93497462e-05,
        5.61553452e-06, 2.03427649e-03]], dtype=float32)>