<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_02-Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial from here:
https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2

In [1]:
import tensorflow as tf
print(tf.__version__)

2.18.0


# **Initialization of Tensor**

In [4]:
x = tf.constant(2)
print(x)
x = tf.constant(4, shape=(1,3), dtype=tf.float64)
print(x)

x = tf.constant([[1,2,3],[4,5,6]]) # 123 dan 456 count as rows (2) 14 25 36 count as columns (3)
print(x)

x = tf.constant((1,2))
print(x)

for i in range(1,4):
    print(" ")

x = tf.ones(3,3)
print(x)
x = tf.zeros(2,3)
print(x)
x = tf.eye(3)
print(x)
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float64)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
 
 
 
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.27254486 -1.0478756  -0.3397357 ]
 [ 0.50508624 -0.61732495 -0.0940145 ]
 [-0.3866868  -0.35602874  1.0611181 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.02627826 0.8970293  0.9562204 ]
 [0.5310054  0.7235744  0.498968  ]
 [0.6851754  0.8878062  0.7009363 ]], shape=(3, 3), dtype=float32)


# **Mathematical Operation**

# **Indexing**

# **Reshaping**