<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_01-Quickstart_for_Begginer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Follow these tutorial: https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb#scrollTo=7FP5258xjs-v

# **Set Up Tensorflow**

In [19]:
import tensorflow as tf
print('tf version:', tf.__version__)

tf version: 2.18.0


# **Load a Dataset**

In [20]:
mnist = tf.keras.datasets.mnist.load_data() #####
(x_train, y_train), (x_test, y_test) = mnist
x_train, x_test = x_train / 255.0, x_test / 255.0

# **Build a machine learning model**

In [21]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])


# print(test_mnist)
print("[] ===== []")
print(model)

[] ===== []
<Sequential name=sequential_2, built=True>


In [22]:
predictions = model(x_train[:1])
print(predictions)
print(tf.argmax(predictions, axis=1))
print(" ")
print(predictions.numpy())

tf.Tensor(
[[ 0.40060028 -0.23755342 -0.6745746   1.8466411   0.17052256 -0.47195786
  -0.29878044  0.59551734 -0.04838347  0.27087614]], shape=(1, 10), dtype=float32)
tf.Tensor([3], shape=(1,), dtype=int64)
 
[[ 0.40060028 -0.23755342 -0.6745746   1.8466411   0.17052256 -0.47195786
  -0.29878044  0.59551734 -0.04838347  0.27087614]]


In [23]:
print(tf.nn.softmax(predictions).numpy())

[[0.09472527 0.05004023 0.03232387 0.402229   0.07525656 0.03958391
  0.04706832 0.11511112 0.06046091 0.08320078]]


In [24]:
predictions = model(x_train[:1]).numpy()
predictions

tf.nn.softmax(predictions).numpy()

array([[0.09472527, 0.05004023, 0.03232387, 0.402229  , 0.07525656,
        0.03958391, 0.04706832, 0.11511112, 0.06046091, 0.08320078]],
      dtype=float32)

In [25]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
print(loss_fn)

<LossFunctionWrapper(<function sparse_categorical_crossentropy at 0x7e65970d7420>, kwargs={'from_logits': True, 'ignore_class': None})>


In [26]:
loss_fn(y_train[:1], predictions).numpy()

np.float32(3.2293327)

In [27]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# **Train and evaluate your model**

In [28]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - accuracy: 0.8601 - loss: 0.4781
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 4ms/step - accuracy: 0.9534 - loss: 0.1541
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9672 - loss: 0.1112
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9731 - loss: 0.0878
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9748 - loss: 0.0758
