<a href="https://colab.research.google.com/github/ImNotDanish05/Tensorflow/blob/main/TensorFlow_Ep_02-Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tutorial from here:
https://www.youtube.com/watch?v=HPjBY1H-U4U&list=PLhhyoLH6IjfxVOdVC1P1L5z5azs0XjMsb&index=2

In [1]:
import tensorflow as tf
print(tf.__version__)
PhysicalDevice = tf.config.list_physical_devices('GPU')
print(PhysicalDevice)
tf.config.experimental.set_memory_growth(PhysicalDevice[0], True)

2.18.0
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


# **Initialization of Tensor**

In [6]:
x = tf.constant(2)
print(x)
x = tf.constant(4, shape=(1,3), dtype=tf.float64)
print(x)

x = tf.constant([[1,2,3],[4,5,6]]) # 123 dan 456 count as rows (2) 14 25 36 count as columns (3)
print(x)

x = tf.constant((1,2))
print(x)

for i in range(1,4):
    print(" ")

x = tf.ones(3,3)
print(x)
x = tf.zeros(2,3)
print(x)
x = tf.eye(3)
print(x)
x = tf.random.normal((3,3), mean=0, stddev=1)
print(x)
x = tf.random.uniform((3,3), minval=0, maxval=1)
print(x)
x = tf.range(start=1, limit=10, delta=3)
print(x)
#This will not change on the print, but its actually for change the type of the value. For example
#For example change from int to float like code down below
x = tf.cast(x, dtype=tf.float64)
print(x)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor([[4. 4. 4.]], shape=(1, 3), dtype=float64)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
 
 
 
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([0 0], shape=(2,), dtype=int32)
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.7296437   0.27943856 -0.33013526]
 [ 0.36843553 -0.42120633 -0.9439669 ]
 [-0.70628077  0.9781292  -0.03738477]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.6271329  0.78312874 0.0840404 ]
 [0.78087974 0.28499532 0.09464157]
 [0.12474895 0.47905755 0.11038733]], shape=(3, 3), dtype=float32)
tf.Tensor([1 4 7], shape=(3,), dtype=int32)
tf.Tensor([1. 4. 7.], shape=(3,), dtype=float64)


# **Mathematical Operation**

In [4]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

"""
Add Function with tf.add() or +
"""
print(" ")
print("Add Function with tf.add() or +")

z = x + y
print(z)
z = tf.add(x, y)
print(z)

"""
Subtract Function with tf.subtract() or -
"""
print(" ")
print("Subtract Function with tf.subtract() or -")

z = tf.subtract(x, y)
print(z)
z = x - y
print(z)

"""
Divide Function with tf.divide() or /
"""
print(" ")
print("Divide Function with tf.divide() or /")

z = tf.divide(x, y)
print(z)
z = x / y
print(z)

"""
Multiply Function with tf.multiply() or *
"""
print(" ")
print("Multiply Function with tf.multiply() or *")

z = tf.multiply(x, y)
print(z)
z = x * y
print(z)

"""
Reduction Function with tf.reduce_sum()
In real math, reduction function is used to calculate the sum of all elements in a matrix.
But in tensorflow, reduction function can be used for tensors with more than one dimension.

The formula for reduction function is:
z = x[0] + x[1] + x[2] + ... + x[n]
For example with x that we already have:
z = 1 + 2 + 3 = 6
The formula for reduction function for x and y is:
z = x[0] + x[1] + x[2] + y[0] + y[1] + y[2]
For example with x and y that we already have:
z = 1 + 2 + 3 + 4 + 5 + 6 = 21
"""
print(" ")
print("Reduction Function with tf.reduce_sum()")

z = tf.reduce_sum([x, y])
print(z)

"""
Dot Product Function with tf.tensordot()
tensordot() is used to calculate the dot product of two tensors.
In real math, dot product is only used for two vectors.
But in tensorflow, dot product can be used for tensors with more than one dimension.
axes=1 means that the dot product will be calculated along the first dimension.

The formula for dot product is:
z = x[0] * y[0] + x[1] * y[1] + x[2] * y[2]
For example with x and y that we already have:
z = 1 * 4 + 2 * 5 + 3 * 6 = 32
"""
print(" ")
print("Dot Product Function with tf.tensordot()")

z = tf.tensordot(x, y, axes=1)
print(z)
z = tf.reduce_sum(x*y, axis=0)
print(z)

"""
Exponent Function with **
In the formula math, exponent function is used to calculate the power of a number.
For example:
z = x ** 5
z = 1 ** 5 = 1
z = 2 ** 5 = 32
z = 3 ** 5 = 243
"""
z = x ** 5
print(z)

"""
Matrix Multiplication Function with tf.matmul() or @
Matrix multiplication is used to multiply two matrices.
The formula for matrix multiplication is you can find it right here:
https://www.youtube.com/watch?v=2spTnAiQg4M
"""

a = tf.random.normal((2,3))
b = tf.random.normal((3,4))
z = tf.matmul(a, b)
print(z)
z = a @ b
print(z)
# The matrix from 2x3 and 3x4 is 2x4

 
Add Function with tf.add() or +
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32)
 
Subtract Function with tf.subtract() or -
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
 
Divide Function with tf.divide() or /
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
tf.Tensor([0.25 0.4  0.5 ], shape=(3,), dtype=float64)
 
Multiply Function with tf.multiply() or *
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
 
Reduction Function with tf.reduce_sum()
tf.Tensor(21, shape=(), dtype=int32)
 
Dot Product Function with tf.tensordot()
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([  1  32 243], shape=(3,), dtype=int32)
tf.Tensor(
[[-0.26819783  0.51244044  1.5498358   0.47258157]
 [-0.15023822  3.6396477   3.1162596   3.4534724 ]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-0.26819783  0.51244044  1.5498358   0.47258157]


# **Indexing**

In [8]:
x = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(x)
print(x[:])
print(x[1:])
print(x[1:5])
print(x[::2])
print(x[1:5:2])
print(x[::-1])
print(x[1::-1])


x = tf.constant([0,1,10,2,3,4,5,6,7,8,9])
indices = tf.constant([0, 3])
x_n = tf.gather(x, indices)
print(x_n)


"""
Index for this is x[row, column]
"""
print(" ")
print("Index for this is x[row, column]")
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])

print(x[0, :])
print(x[0:1, :])
print(x[:, 0])
print(x[:, 0:1])
print(x[1,:])
print(x[0:2,:])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)
tf.Tensor([1 0], shape=(2,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
 
Index for this is x[row, column]
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)
tf.Tensor(
[[1]
 [3]
 [5]], shape=(3, 1), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


# **Reshaping**

In [15]:
x = tf.range(10)
x = tf.reshape(x, (2,5))
print(x)

x = tf.range(9)
print(x)

x = tf.reshape(x, (3,3))
print(x)

x = tf.transpose(x)
print(x)

x = tf.transpose(x)
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
